### ISSUE TITLE
Chrome headless support

### ISSUE THREAD

**Issue by akatz** [trentmwillis/ember-exam#101]
It seems that when trying to use chrome headless I get a bunch of port already in use errors. I suspect this is because chrome headless requires you to use the command line arg `--remote-debugging-port=9292`. When `ember exam` spawns multiple browsers it must just reuse the testem config and thus the subsequent browsers cannot actually bind to the port they need.

**Comment by trentmwillis** [comment]
This sounds legit, but I cannot reproduce it locally. Do you have a reproduction you could share with me? I suspect that if this is an issue, it will need to be fixed in Testem though.

**Comment by akatz** [comment]
So more information ( I should have include this originally ) This is specifically when using it inside of docker. Because in docker I need to use `--no-sandbox` mode it was behaving differently than without. I have no determined that when launching chrome via testem with `--no-sandbox` mode it launches twice the number of chrome instances `--split=4` winds up with 8 running chrome instances.

It does appear to be a testem issue, because I can reproduce this with simply `ember test`
