### ISSUE TITLE
Better feedback for ember-exam@0.6 and ember-cli-qunit@4.

### ISSUE THREAD

**Issue by rwjblue** [trentmwillis/ember-exam#102]
This switch is pretty trolling for users. We made heavy note of the requirements to call `start()` in ember-cli release notes, but didn't mention anything about ember-exam. I think we can probably make it a bit nicer...

I'd suggest that we create a patch release of ember-exam@0.6.x that uses `ember-cli-version-checker` to detect if the host app is using `ember-cli-qunit@4` and issue a loud warning (or even error) suggesting that they need to upgrade to ember-exam@0.7.

**Comment by rwjblue** [comment]
@trentmwillis - Do you think ^ is a good plan?

**Comment by trentmwillis** [comment]
This seems reasonable to me :+1:

**Comment by gauravsharma-avalara** [comment]
Hi
I have installed ember exam updated ember-cli-qunit@4 and test_helper.js but I am not able to run tests in split mode using ember exam. It gives so many errors. Please suggest what could be the reason for this.

//test-helper.js
import resolver from './helpers/resolver';
import registerSelectHelper from './helpers/register-select-helper';
registerSelectHelper();
import {
  setResolver,
} from 'ember-qunit';
import loadEmberExam from 'ember-exam/test-support/load';
loadEmberExam();
import { start } from 'ember-cli-qunit';
start();
window.cup_ = _;
setResolver(resolver);

<img width="1193" alt="screen shot 2017-08-18 at 10 23 47 am" src="https://user-images.githubusercontent.com/30595363/29444711-66700da0-83ff-11e7-8642-68181bb0e307.png">
<img width="723" alt="screen shot 2017-08-18 at 10 25 08 am" src="https://user-images.githubusercontent.com/30595363/29444736-a4f32968-83ff-11e7-8a84-65a3c4739747.png">
<img width="542" alt="screen shot 2017-08-18 at 10 25 39 am" src="https://user-images.githubusercontent.com/30595363/29444738-a7e4f962-83ff-11e7-9a73-c3ae3579b0dd.png">

**Comment by gaurav0210** [comment]
Hi
I have installed ember exam updated ember-cli-qunit@4 and test_helper.js but I am not able to run tests in split mode using ember exam. It gives so many errors. Please suggest what could be the reason for this.

//test-helper.js
import resolver from './helpers/resolver';
import registerSelectHelper from './helpers/register-select-helper';
registerSelectHelper();
import {
setResolver,
} from 'ember-qunit';
import loadEmberExam from 'ember-exam/test-support/load';
loadEmberExam();
import { start } from 'ember-cli-qunit';
start();
window.cup_ = _;
setResolver(resolver);


<img width="1193" alt="screen shot 2017-08-18 at 10 23 47 am" src="https://user-images.githubusercontent.com/11131500/29444858-94ea1634-8400-11e7-9eae-8be734d373a8.png">
<img width="723" alt="screen shot 2017-08-18 at 10 25 08 am" src="https://user-images.githubusercontent.com/11131500/29444863-9a61297c-8400-11e7-8e39-a461ce72d739.png">
<img width="542" alt="screen shot 2017-08-18 at 10 25 39 am" src="https://user-images.githubusercontent.com/11131500/29444865-9cf5c706-8400-11e7-968c-3ded7ebc1735.png">

**Comment by trentmwillis** [comment]
A little late, but I just published version 0.6.3 that addresses this.

**Comment by rwjblue** [comment]
Thank you. I completely forgot to do the work mentioned above. Sorry to let that fall back on you.
