### ISSUE TITLE
ember exam expects `ember` binary on path

### ISSUE THREAD

**Issue by briangonzalez** [trentmwillis/ember-exam#109]
We're seeing `command not found: ember` when trying to run ember exam.

It looks like ember exam is expecting ember to be on `PATH`, but this may not always be the case. Any concerns with invoking ember from within `node_modules`?

https://github.com/trentmwillis/ember-exam/blob/67e400a842010219b5bab38f4b70b95ab05011fb/lib/commands/exam/iterate.js#L77

**Comment by ro0gr** [comment]
> It looks like ember exam is expecting ember to be on PATH

node also resolves all the binaries located in the `${projectDir}/node_modules/.bin/`. 
`ember-cli` usually provides `node_modules/.bin/ember` binary. Do you have `ember-cli` in you package.json?
