### ISSUE TITLE
Allow testing of engines

### ISSUE THREAD

**Issue by amk221** [trentmwillis/ember-exam#118]
Engines can already be tested, but if the engine is Lazy, it needs to be loaded separately in the test suite (as per [these instructions](https://github.com/ember-engines/ember-engines/issues/388#issuecomment-327286341)). This works fine, but will fail to run via Ember Exam

**Comment by trentmwillis** [comment]
Can you provide a reproduction? It is likely that there is something incorrect about the way you have things configured as all Ember Exam does is modify which modules get `require`d. So if it works without Ember Exam then it should work with it.

**Comment by amk221** [comment]
Yeh you're right, this does work with fresh ember-cli app (Example [here](https://github.com/amk221/-ember-exam-engines)).
