### ISSUE TITLE
--split 4 --parallel seems to result in 4x the number of tests runs (with mocha)

### ISSUE THREAD

**Issue by stefanpenner** [trentmwillis/ember-exam#124]
Steps to reproduce:

```
git clone git@github.com:stefanpenner/es6-promise.git
cd es6-promise
yarn
ember install ember-exam
ember exam --split 4 --parallel
```

Notes:

* this project uses mocha ( i haven't seen this issue with qunit)

**Comment by devinus** [comment]
Also seeing this. To extrapolate further, `--split 2 --parallel` runs 2x the tests, etc.

**Comment by trentmwillis** [comment]
@stefanpenner looks like the `es6-promise` repo doesn't use `ember-cli-mocha` though, correct? The partitioning feature only works when using an addon that uses the `ember-cli-test-loader` for loading tests.

@devinus are you referring to seeing this in the same project or a different project?

**Comment by stefanpenner** [comment]
> looks like the es6-promise repo doesn't use ember-cli-mocha though, correct? The partitioning feature only works when using an addon that uses the ember-cli-test-loader for loading tests.

Oh, i did not realize this (seems perfectly reasonable requirement). Is this documented?

**Comment by trentmwillis** [comment]
Not the bit about `ember-cli-test-loader`, but the readme does specify that either `ember-cli-qunit` or `ember-cli-mocha` must be used:

> Ember Exam is an addon to allow you more control over how you run your tests **when used in conjunction with Ember CLI QUnit or Ember CLI Mocha***.

*_Emphasis added_.

Do you think this should be highlighted more?

**Comment by stefanpenner** [comment]
@trentmwillis LGTM :)
