### ISSUE TITLE
files in tests/helpers/ ending with -test.js being dropped

### ISSUE THREAD

**Issue by stefanpenner** [trentmwillis/ember-exam#14]
likely do to https://github.com/trentmwillis/ember-exam/blob/master/lib/utils/tests-processor.js#L14 (as @trentmwillis pointed out)

**Comment by trentmwillis** [comment]
The check was original intended to mimic the behavior given by `ember-cli-test-loader`, but we can relax it a bit and make sure the test doesn't reside in the `tests/helpers` directory.

**Comment by trentmwillis** [comment]
Closed via #20, this is now supported by using the `--use-ast=false` flag. This will eventually become the default after a bit more testing.
