### ISSUE TITLE
support for code-coverage

### ISSUE THREAD

**Issue by stefanpenner** [trentmwillis/ember-exam#18]
Currently, I don't believe coverage such as ember-cli-blanket supports. This may require changes no both sides, but maybe we can track that here.

**Comment by yahooP** [comment]
@stefanpenner can you expand on what would need to be added from both ends to support this?

**Comment by trentmwillis** [comment]
The approach we're pursuing is documented in this Ember-CLI RFC: https://github.com/ember-cli/rfcs/pull/57

Should've referenced this issue before.

**Comment by trentmwillis** [comment]
Code coverage is now supported in [ember-cli-code-coverage](https://github.com/kategengler/ember-cli-code-coverage). I think the approach taken there will be suitable for other addons/libraries if integration is desired.

The short summary is, coverage should be done as normal and just merge the multiple reports at the end.

**Comment by yahooP** [comment]
This is an automatically generated message.

paulius@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Comment by avacado** [comment]
How can I get a code coverage report if I run npm run exam?
