### ISSUE TITLE
[v0.4.1] Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by Arkham** [trentmwillis/ember-exam#25]
Hi there,

first of all thanks for this amazing addon, it's great :)

I just upgraded from 0.3.1 to 0.4.1and the tests don't run anymore but show this message instead. Poking into the source I think the cause of the error is this snippet: https://github.com/trentmwillis/ember-exam/blob/master/vendor/ember-exam/test-loader.js#L60-L78

In my tests setup I have disabled linting tests, so `groups` is never initialized to an array of arrays and therefore the code tries to push an object onto undefined.

**Comment by trentmwillis** [comment]
Thanks for reporting @Arkham! This should be a relatively simple fix and I'm in the process of writing tests for all that test loader code as well, so I'll work it into that effort.

**Comment by trentmwillis** [comment]
Should be fixed now. Released in version 0.4.2.

**Comment by Arkham** [comment]
Thanks @trentmwillis much appreciated!
