### ISSUE TITLE
Integrate with Ember Try?

### ISSUE THREAD

**Issue by trentmwillis** [trentmwillis/ember-exam#30]
Seems like this could be a beneficial feature. More thoughts later on use cases.

**Comment by martndemus** [comment]
Maybe just a little guide how to set this up with Ember Try would be sufficient:
https://github.com/ember-cli/ember-try#configuration-files

**Comment by trentmwillis** [comment]
Didn't realize you could specify a command to run! Awesome, will test it out myself and then add some documentation.

**Comment by martndemus** [comment]
Yes, though I believe this hasn't been the case until recently.

**Comment by trentmwillis** [comment]
Closed via #39
