### ISSUE TITLE
Allow --split=1

### ISSUE THREAD

**Issue by raytiley** [trentmwillis/ember-exam#43]
I'm having issues on appveyor with split tests in firefox. What i'm trying to accomplish is run my test suite in different browsers in parallel, so I don't need / want to split the the test suite into multiple files. Would you be open to changing `ember-exam` to allow this?

**Comment by trentmwillis** [comment]
Not sure I understand the problem, if you don't want to split the tests, just omit the `--split` option and it should run the test suite normally.

**Comment by raytiley** [comment]
in order to use `--parallel` the command requires that `--split` be greater than 1

**Comment by trentmwillis** [comment]
The `--parallel` option only parallelizes your tests, so if you don't split them then it doesn't make any sense (how can you parallelize a single task?).

I think I understand that what you want is to parallelize browsers, which is something that Testem itself can handle through [config options](https://github.com/testem/testem/blob/master/docs/config_file.md#config-level-options). In particular, what I think you want is to specify values for `launch_in_ci` and `parallel`. For example:

```json
{
  "launch_in_ci": [ "FireFox", "Chrome", "PhantomJS" ],
  "parallel": "3"
}
```

**Comment by raytiley** [comment]
Doh... yeah.. I didn't realize that just running ember with the parallel
flag would launch both.

Thanks!

=ray
