### ISSUE TITLE
Feature Request - split acceptance tests into one split

### ISSUE THREAD

**Issue by JonForest** [trentmwillis/ember-exam#44]
One of the issues we're facing with using this component is that our acceptance tests call a controlled API with fixtured data.  Each test builds and tears down that data.  When running acceptance tests in parallel, this causes problems.

It would be great if we could run the acceptance tests in one 'split' and all our unit/integration tests in another split or splits.

Is this the kind of thing that would be useful?  Or is it maybe better approached by running two `ember exam` commands with filtering?  The issue there may be that while it's easy to filter for 'only acceptance' tests, potentially it's more difficult to filter for 'everything but acceptance tests'

**Comment by trentmwillis** [comment]
So this is not currently supported out of the box, but I could see this being a cool feature to add. Basically allow segmentation by filter, maybe a comma separated list of filters like:

```bash
$ ember exam --segments "acceptance, !acceptance"
```

Then the individual splits/parallel can occur on each segment. Does that seem reasonable to you?

---

To help you get around this currently, you can do something like you suggested and running two different tasks **_or_** you can actually set up your own parallel runs by doing something like the following in your Testem config:

```json
{
  "test_page": [
    "/tests/index.html?filter=acceptance",
    "/tests/index.html?filter=!acceptance"
  ],
  "parallel": 2
}
```

And then just run `ember exam` or `ember test`. This is more or less what the `--parallel` flag does under the hood, just without the `filter` params.

Filtering is a lot more powerful than people realize now that you can do negation filtering (as seen above) and regex filtering (e.g., `?filter=/unit|integration/i`). See the [QUnit docs](http://api.qunitjs.com/QUnit.config/) for more details.

**Comment by trentmwillis** [comment]
My goal with this addon is to enable developers to avoid having to fiddle with configurations, so I think there is a good use case here. Especially if you wanted to do something to the effect of testing specific areas of your code base or maybe runs tests with certain features on/off. I also don't think it'll be difficult to add.

I would probably revamp the above to take in arbitrary query params so you could achieve something like:

```bash
$ ember exam --segments "enableOptionalFeatures=true, disableOptionalFeatures=false"
```

**Comment by trentmwillis** [comment]
Closing this. Didn't wind up adding a new feature, but now that we read in the actual Testem config, consumers can define multiple `test_page` values and they'll still work with all of Ember Exam's features.

Also, [added a brief mention of this to the readme](https://github.com/trentmwillis/ember-exam/pull/53).
