### ISSUE TITLE
Automatically run all partitions 

### ISSUE THREAD

**Issue by gpt559** [trentmwillis/ember-exam#45]
I'm interested in this add-on because my current project has a couple hundred tests and if we just call
```ember test``` phantomjs will crash. 

I would like to use this plugin and just type: 

```ember exam --split=3``` and have it run through all three partitions, not just the first one. 

Right now it looks like i have to call:
```
ember exam --split=3 --partition=1
ember exam --split=3 --partition=2
ember exam --split=3 --partition=3
```

Is this correct? If I have to call it three times will ember build three times?

**Comment by trentmwillis** [comment]
Use the [`--parallel` option](https://github.com/trentmwillis/ember-exam#split-test-parallelization): `ember exam --split=3 --parallel`. That will run all three partitions in parallel with 3 browser instances.

**Comment by gpt559** [comment]
Thanks for the quick reply. I tried that but I'm guessing something is wrong with my testem setup because that isn't working for me. I did add the parallel param to the testem.js file, but I probably have some bigger issues on my end. 

Thanks again!
