### ISSUE TITLE
Mocha support

### ISSUE THREAD

**Issue by fotinakis** [trentmwillis/ember-exam#47]
Hey Trent, I'm curious if there is workaround or planned official for getting ember-exam to work with a Mocha test suite? Right now we simply get `QUnit is not defined` when trying, I wanted to ask before digging further.

**Comment by trentmwillis** [comment]
I'm not currently pursuing it (mainly cause I don't have any experience using Mocha with Ember), but I would definitely welcome PRs to help support it!

**Comment by marsh73** [comment]
Would be really great to be able to do this. Can you point to a starting point to integrate? I will take a look myself if I can but any guidance would be a great help.

**Comment by trentmwillis** [comment]
The biggest integration is the [`TestLoader`](https://github.com/trentmwillis/ember-exam/blob/master/vendor/ember-exam/test-loader.js) which is what handles "splitting" modules based on some URL parameters. Currently this is coupled to QUnit's `urlParams`, so it would need to be made framework agnostic. Additionally, you'll need to make sure all the modifications/assumptions in the `ember-exam` `TestLoader` work with [`ember-cli-mocha`s implementation](https://github.com/switchfly/ember-cli-mocha/blob/master/vendor/ember-cli-mocha/test-loader.js).

That's probably the bulk of the work, as that will enable the `split`, `partition`, and `parallel` options.

The `random` option is essentially just a URL param which QUnit supports ([see `seed`](https://api.qunitjs.com/QUnit.config/)), but it doesn't look like Mocha has [support for randomized test order yet](https://github.com/mochajs/mocha/issues/902). So maybe we add a check to see if using Mocha, then warn that randomization isn't supported currently?

**Comment by trentmwillis** [comment]
@fivetanley are you still pursuing this?

**Comment by trentmwillis** [comment]
I've opened a work-in-progress PR for this. Hoping to land by sometime this weekend!

**Comment by trentmwillis** [comment]
Mocha support has landed! Will be available in the next release (pending some minor improvements)
