### ISSUE TITLE
Fix ember-cli-test-loader require

### ISSUE THREAD

**Issue by trentmwillis** [trentmwillis/ember-exam#48]
Pretty sure [this is going to break](https://github.com/trentmwillis/ember-exam/blob/43eb7603572241c28079ee9e17843dcdfe36a7d8/vendor/ember-exam/test-loader.js#L14) with the recent change of `ember-cli-test-loader` moving to NPM.

See a reference of the [fix in `ember-cli-qunit`](https://github.com/ember-cli/ember-cli-qunit/blob/7b45b1bb40468ef07c5f969013f7fb9b18d314d8/vendor/ember-cli-qunit/test-loader.js#L4-L10). Easy to do, just need someone to do it and verify behavior.

**Comment by chriskrycho** [comment]
:raises hand: I'll see if I can take a swing at this sometime this weekend.

**Comment by trentmwillis** [comment]
@chriskrycho thanks! Best way to verify this would probably be to upgrade the addon to use `ember-cli@2.7.0`

**Comment by chriskrycho** [comment]
👍🏼 Taking a stab at it now!

**Comment by cibernox** [comment]
@chriskrycho let me know if you need help, I wanted to update my app to 2.7 but I'm blocked by this.

**Comment by chriskrycho** [comment]
@cibernox, if you want to pick up and run with the PR I started (#49), please do. I got started, but ran into a [test failure](https://travis-ci.org/trentmwillis/ember-exam/jobs/148574265#L458) that I didn't have time to chase down. That should hopefully have a lot of the package.json grunt work done, if nothing else.

**Comment by trentmwillis** [comment]
Should be fixed now with `0.4.5`.
