### ISSUE TITLE
document percy support

### ISSUE THREAD

**Issue by kellyselden** [trentmwillis/ember-exam#61]
This is not a request but an offer. I think I am the first/only person to get percy.io working with ember-exam. Here is the complete list of changes required: https://github.com/kellyselden/package-hint-historic-resolver/pull/159

You may want to add it to the docs, or just close this issue and allow github issue searches to find this issue.

**Comment by trentmwillis** [comment]
Thanks for the example! I'm not gonna adds this to the docs at this point in time, since it seems like an uncommon use case, but having this issue and a link to the [Percy docs for parallel tests](https://percy.io/docs/learn/parallel-tests) is beneficial.
