### ISSUE TITLE
Arguments not passed to ember test

### ISSUE THREAD

**Issue by amk221** [trentmwillis/ember-exam#73]
Our test reporter defaults to `xunit`. I have a grunt task that runs:
`ember test --reporter=tap` however, when I switch to ember exam:
`ember exam --random --reporter=tap` the reporter is not sent to `ember test`.

For ember exam to be a "drop in replacement", I think the arguments need to be forwarded on.

```javascript
// testem.js
module.exports = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed&dockcontainer&notifications",
  "disable_watching": true,
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ],
  "reporter": "xunit",
  "report_file": "tests/results.xml"
};
```

**Comment by trentmwillis** [comment]
This is likely due to weirdness in the argument parsing. Can you try using `ember exam --reporter=tap --random` instead?

**Comment by amk221** [comment]
ah yeh :) that works.

**Comment by trentmwillis** [comment]
Great. I'll update the readme to make sure this "gotcha" is mentioned. It's a side-effect of the fact that `--random` can be used with or without an additional following argument. So when doing `--random --reporter=tap` the parsing lib was likely treating it as if `--random="--reporter=tap"` was passed.
