### ISSUE TITLE
Reuse seed value when running -serve

### ISSUE THREAD

**Issue by samselikoff** [trentmwillis/ember-exam#75]
Is this possible? If I've found a useful seed I'd like to be able to run the test server with it, so I can debug in the browser.

Thanks for this awesome addon!

**Comment by trentmwillis** [comment]
Derp, after looking into the above, I realized I was using `ember test` instead of `ember exam` haha.

Doing `ember exam --serve --random` will put the seed value into the URL of the browser. If you have any more issues, let me know!
