### ISSUE TITLE
Can't find variable withFeature

### ISSUE THREAD

**Issue by dylanfoster** [trentmwillis/ember-exam#76]
Trying to use ember-exam with [ember-feature-flags](https://github.com/kategengler/ember-feature-flags) and it looks like maybe the feature flag initializer doesn't get run when using the `--split` option

**Comment by trentmwillis** [comment]
Can you elaborate more? When doesn't it get run? Is this an acceptance, integration, or unit test? In general, this doesn't sound like an ember-exam issue and more likely a test suite with improperly encapsulated tests.

**Comment by dylanfoster** [comment]
This was in an acceptance test

```javascript
describe("xxx", function () {
  beforeEach(function () {
    withFeature("foo");
  });
});
```

**Comment by trentmwillis** [comment]
Is the `withFeature` helper being imported in your test or in you `test-helper.js` file?

**Comment by dylanfoster** [comment]
no, and that fixed it.. thanks for the pointer. I had assumed that `Ember.Test.registerHelper` would register a global helper

**Comment by trentmwillis** [comment]
It will, but it has to be executed first, so if it isn't imported it won't ever execute ([reference from the docs about usage](https://github.com/kategengler/ember-feature-flags#withfeature)).
