### ISSUE TITLE
ember exam does not return a negative exit code when tests fail in iterate mode

### ISSUE THREAD

**Issue by jonathanong** [trentmwillis/ember-exam#79]
it logs it, but does not `process.exit(1)`. this has been giving us false positives in our tests.

**Comment by trentmwillis** [comment]
Thanks for reporting, this is an oversight on my part. Definitely a bug; would appreciate if you could file a PR to fix!

**Comment by jonathanong** [comment]
unfortunately, the "view" logic is combined with the "business logic". i would have to refactor quite a bit to do it properly, and refactoring a lot always makes merging a PR less likely :)

**Comment by trentmwillis** [comment]
This has been fixed and released in `0.6.1`.
