### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by trentmwillis** [trentmwillis/ember-exam#8]
One of the core features I hoped to introduce with this addon is parallelization of tests. There are lots of considerations that went into this, and it finally resulted in needing support from [Testem](https://github.com/testem/testem).

The feature will leverage the new [multiple test pages in parallel](https://github.com/testem/testem/pull/800) config option from Testem once it is released. So, opening this issue to make sure the updates here happen once that is available.

**Comment by paulius005** [comment]
Is there any help that you would need with this going out? Or should we hang tight until the support from Testem comes?

**Comment by trentmwillis** [comment]
Hang tight. Just got news today that the new Testem feature is released, so I plan to work on this sometime within the next week hopefully.

**Comment by trentmwillis** [comment]
This has been completed and is available in version 0.2.1.
