### ISSUE TITLE
Investigate test loader changes in ember-cli-qunit@4

### ISSUE THREAD

**Issue by rwjblue** [trentmwillis/ember-exam#81]
Just a reminder to double check to the changes made in https://github.com/ember-cli/ember-cli-qunit/pull/176 to make sure ember-exam still functions properly.

**Comment by trentmwillis** [comment]
So the ember-cli-qunit changes do cause problems here, I'm going to investigate a way to make it backwards and forwards compatible.

**Comment by calderas** [comment]
I think parallelization is no longer working on ```ember-cli v2.13.x```  due to this change since it comes with ```ember-cli-qunit v4.0.x```  by default.

**Comment by trentmwillis** [comment]
Seems likely. I'll try to find some time to look into it soon but would greatly appreciate if someone else could investigate before then.

**Comment by scottkidder** [comment]
I'm seeing this as well. Running `ember exam --split 4 --parallel` looks like each test is being run 4 times.

**Comment by calderas** [comment]
I can confirm ```TestLoader.prototype.loadModules``` is not being executed when using ```ember-cli-qunit v4.0.x``` 

That means ember exam runs the whole test suite N times when using ``` --parallel --split=N```

I guess this needs to be refactored to support the new behavior on cli-qunit.
https://github.com/trentmwillis/ember-exam/blob/master/vendor/ember-exam/test-loader.js#L55-L59

**Comment by trentmwillis** [comment]
Looks like `ember-cli-qunit@4.0.0` changed the order of execution of some things, thus `test-helper.js` runs first and calls `start()` which runs the `TestLoader`. This happens before ember-exam can monkeypatch the `TestLoader` class. I want to update this addon to take a more explicit approach, similar to `ember-cli-qunit`.

**Comment by YoranBrondsema** [comment]
I'm encountering the same issue, i.e. the whole suite is executed when splitting. @trentmwillis anything I can do to help getting your PR in master?

**Comment by trentmwillis** [comment]
I just released `v0.7.0` which should make it possible to work with `ember-cli-qunit@4.0.0`. [Note you'll need to invoke a new `loadEmberExam` function though.](https://github.com/trentmwillis/ember-exam#note-on-version-070)

**Comment by YoranBrondsema** [comment]
@trentmwillis Awesome, works for me. Thanks so much!

**Comment by scottkidder** [comment]
Works for me for the most part. The only issue I've encountered (in parallel only) is that somehow my custom inflector rules not being respected. I am following this pattern: https://guides.emberjs.com/v2.13.0/models/customizing-adapters/#toc_pluralization-customization

I have a model 'bars' that is uncountable that is referenced through a hasMany on 'foo'. When running the model and serializer tests for 'foo' the test fails saying:
No model was found for for 'bar'

These tests do not fail when running without parallelization.
