### ISSUE TITLE
Only max of 2 browser instances are running

### ISSUE THREAD

**Issue by GCheung55** [trentmwillis/ember-exam#85]
I'm only seeing two instances of PhantomJS running at a time. With `-s`, I see more instances. I'm not sure if this is a bug in `ember-exam` or `testem.js`.

ember-cli@2.12.1
ember-source@2.12.0
ember-exam@0.6.2

Command:
```
ember exam --split=10 --parallel --silent
```

**Comment by trentmwillis** [comment]
What is your Testem config? Specifically, what is the value of `parallel` inside your `testem.js` or `testem.json` file?

**Comment by GCheung55** [comment]
@trentmwillis good question. I saw a bunch of configs with `parallel: -1` and didn't know that I needed to add that to my config.

After adding `parallel` I saw >2 browser instances.

Closing.
