### ISSUE TITLE
Custom Inflector Rules not respected

### ISSUE THREAD

**Issue by scottkidder** [trentmwillis/ember-exam#95]
I've encountered (in parallel only) my custom inflector rules not being respected. I am following this pattern: https://guides.emberjs.com/v2.13.0/models/customizing-adapters/#toc_pluralization-customization

I have a model 'bars' that is uncountable that is referenced through a hasMany on 'foo'. When running the model and serializer tests for 'foo' the test fails saying:
No model was found for for 'bar'

The tests both specify needs: [ 'model:bars']

These tests do not fail when running without parallelization.

I am on:
ember-exam@0.7.0
ember-cli@2.14.0-beta.2
ember-cli-qunit@4.0.0

**Comment by YoranBrondsema** [comment]
Do the failing tests run in isolation, i.e. when you run just that single test? If not, it might be that the failing tests need a dependency that happens to be supplied by another test file. When the tests run in parallel, if the failing and "supplier" test are run in different partitions, the dependency is no longer supplied.

**Comment by trentmwillis** [comment]
Can you provide a reproduction of your issue? In general, I highly doubt that this addon is the root cause here. All Ember Exam does during tests is change which test modules get `require`d by the `TestLoader`.

The route @YoranBrondsema mentions is also worth investigating.

**Comment by scottkidder** [comment]
@YoranBrondsema spot on. It appears my Acceptance tests were the only way the import of my `custom-inflector-rules.js` was happening because I was doing it in `app.js`

I just needed to import my rules in `test-helper.js`

Maybe the guide @ https://guides.emberjs.com/v2.13.0/models/customizing-adapters/#toc_pluralization-customization should mention this?

**Comment by trentmwillis** [comment]
@scottkidder might be worth opening an issue on the guides repo for that: https://github.com/emberjs/guides
